# Spring Boot Configuration
spring.application.name=transaction-wallet-idVerification-system

# Database Configuration (H2)
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:noUsername}
spring.datasource.password=${DB_PASSWORD:noPassword}

# H2 Console (nur für Development)
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:false}

# Server Configuration
server.port=${SERVER_PORT:8080}

# Logging
logging.level.de.yannickPoeschl.transaction_Wallet_IdVerification_System=${LOG_LEVEL:INFO}
logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:WARN}